global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai-observatory"
    metrics_path: /metrics
    static_configs:
      - targets: ["EC2_A_PRIVATE_IP:30080"]
        labels:
          environment: "student"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
